name: release-from-dispatch
run-name: 'Release ${{ inputs.version_number }}'

on:
  workflow_dispatch:
    inputs:
      version_number:
        description: 'Version number (e.g., v1.0.0, v1.0.0-pre, v1.0.0-pre1)'
        required: true
      skip_tests:
        description: 'Skip QA acceptance tests, define value to `true` to explicitly skip'
  
jobs: 

  validate-version-input:
    runs-on: ubuntu-latest
    steps:
      - name: Validation of version format
        run: |
          echo "${{ inputs.version_number }}" | grep -P '^v\d+\.\d+\.\d+(-pre[A-Za-z0-9-]*)?$'

  # run accepetance test if not skipped and is definitive release.  
  run-qa-acceptance-tests:
    needs: [ validate-version-input ]
    if: needs.validate-version-input.result == 'success' && inputs.skip_tests != 'true' && !contains(inputs.version_number, 'pre')
    runs-on: ubuntu-latest
    steps:
      - name: Simulate a failing step
        run: |
          echo "Tests are successful"
      
  fake-release:
    runs-on: ubuntu-latest
    needs: [ validate-version-input, run-qa-acceptance-tests ]
    if: ${{ always() && needs.validate-version-input.result == 'success' && (needs.run-qa-acceptance-tests.result == 'skipped' || needs.run-qa-acceptance-tests.result == 'success') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Unshallow
        run: git fetch --prune --unshallow
      - uses: rickstaa/action-create-tag@v1.7.2 # will fail if existing tag is present
        id: "tag_create"
        with:
          tag: ${{ inputs.version_number }}
          # gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          # gpg_passphrase: ${{ secrets.PASSPHRASE }}
      - name: Echo a Test Message
        run: echo "simulating execution of release"