name: release-from-dispatch
on:
  workflow_dispatch:
    inputs:
      version_number:
        description: 'Version number (e.g., v1.0.0, v1.0.0-pre, v1.0.0-pre1)'
        required: true
      skip_tests:
        description: 'Define value to true to explicitly skip test execution.'
  
jobs: 
  run-qa-acceptance-tests:
    if: ${{ github.event.inputs.skip_tests != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Simulate a failing step
        run: |
          echo "This step will fail"
          exit 1
      
  fake-release:
    runs-on: ubuntu-latest
    needs: [ run-qa-acceptance-tests ]
    if: ${{ github.event.inputs.skip_tests == 'true' || success() }}
    steps:
        - name: Echo a Test Message
          run: echo "simulating execution of release"