name: Run Script and Commit Changes

# Unifies logic for running a script and commit specific changes to master. Used during release process and for updating changelog on merged PRs.
on:
  workflow_call:
    inputs:
      script_call:
        required: true
        type: string
      file_to_commit:
        required: true
        type: string
      commit_message:
        required: true
        type: string

jobs:
  run_script_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
        with:
          fetch-depth: 0
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491
        with:
          go-version-file: 'go.mod'

      - name: Run specified script
        run: ${{ inputs.script_call }}

      - name: Commit changes
        run: |
          if [[ $(git status --porcelain) ]]; then
            git pull
            git config --local user.email svc-api-experience-integrations-escalation@mongodb.com
            git config --local user.name svc-apix-bot
            git add ${{ inputs.file_to_commit }}
            git commit -m "${{ inputs.commit_message }}"
            git push
          else
            echo "No changes to commit."
          fi
